# Generated by Django 4.1.7 on 2023-03-07 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=70)),
                ('prompt', models.CharField(max_length=500)),
                ('is_private', models.BooleanField(default=True)),
                ('image0', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('image1', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('image6', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('image7', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('image8', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('liked_by', models.ManyToManyField(editable=False, related_name='post_like', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
