# Generated by Django 4.1.7 on 2023-03-07 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AIArtArena', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image0',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ai-images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ai-images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ai-images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ai-images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ai-images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image5',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ai-images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image6',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ai-images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image7',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ai-images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image8',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ai-images/'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.URLField(editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
