# Generated by Django 4.1.7 on 2023-03-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIArtArena', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default='8b6c20f04ca047548da4ba7cc9eb2782', editable=False, primary_key=True, serialize=False),
        ),
    ]
