# Generated by Django 4.1.7 on 2023-03-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIArtArena', '0011_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image0',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image5',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image6',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image7',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image8',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/'),
        ),
    ]
